---
# Install system packages
- name: Add custom Galaxy PPA (used for nginx package)
  apt_repository: repo="ppa:galaxyproject/nginx" update_cache=no

- name: Add Docker repository key
  apt_key: url="https://apt.dockerproject.org/gpg" id="2C52609D"
  when: configure_docker

- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' update_cache=no #'
  when: configure_docker

- name: Update APT cache
  apt: update_cache=yes

- name: Install required system packages
  apt: pkg={{ item }} state={{ apt_package_state }}
  with_items:
    - ant
    - atop
    - axel
    - bioperl
    - cmake
    - curl
    - g++
    - gcc
    - gfortran
    - git-core
    - htop
    - iftop
    - iotop
    - ipython
    - libffi-dev
    - liblapack-dev
    - libncurses5-dev
    - libopenblas-dev
    - libpam0g-dev
    - libpq-dev
    - libsparsehash-dev
    - make
    - mercurial
    - nginx-extras
    - nmon
    - openssh-server
    - patch
    - postgresql
    - postgresql
    - postgresql-client
    - postgresql-plpython-9.3
    - python-boto
    - python-dev
    - python-prettytable
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - postgresql-server-dev-9.3
    - rsync
    - slurm-drmaa-dev
    - supervisor
    - swig
    - sysstat
    - unzip
    - vim
    - wget
    - zlib1g-dev

- name: Install Docker package
  apt: pkg={{ item }} state={{ apt_package_state }}
  with_items:
    - "{{ docker_package }}"
  when: configure_docker and install_packages
